name: 'Main Branch Actions'

on:
  push:
    # Only initiate the workflow when the main branch is pushed to
    branches:
      - main

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Required for testing actions that use OIDC to access other resources (like npm publish)
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          # It seems this may be required for OIDC to work properly, because it pulls in something
          # related to auth according to the documentation: https://github.com/actions/setup-node
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      # We need later than 11.5.1 of NPM for OIDC support
      - name: Publish to npm
        run: |
          npm install -g npm@latest
          npm publish --access public
