name: 'Main Branch Actions'

on:
  push:
    # Only initiate the workflow when the main branch is pushed to
    branches:
      - main

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Required for testing actions that use OIDC to access other resources (like npm publish)
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          # It seems this may be required for OIDC to work properly, because it pulls in something
          # related to auth according to the documentation: https://github.com/actions/setup-node
          registry-url: 'https://registry.npmjs.org'

      - name: Setup yarn 4
        run: corepack enable

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-cache-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-v1-

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      # We need later than 11.5.1 of NPM for OIDC support
      - name: Publish to npm
        run: |
          npm install -g npm@latest
          npm publish --access public
