name: 'Pull Request Actions'

on:
  pull_request:
    # Only initiate the workflow when a PR is opened, or committed to.
    branches:
      - main

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Required for testing actions that use OIDC to access other resources (like npm publish)
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Run Linting
        run: pnpm lint

      - name: Dry run publish to NPM
        run: npm publish --access public --dry-run
